# Generated by Django 6.0.3 on 2026-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmenupermission',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
