# Generated by Django 6.0.3 on 2026-03-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'İhale', 'verbose_name_plural': 'İhaleler'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Teklif', 'verbose_name_plural': 'Teklifler'},
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Menu name')),
                ('url_name', models.CharField(help_text="'name' parameter in urls.py (auctions:list)", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenus', to='auctions.menu', verbose_name='Üst Menü')),
            ],
            options={
                'verbose_name': 'Menü',
                'verbose_name_plural': 'Menüler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='auth.group')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='auctions.menu')),
            ],
            options={
                'verbose_name': 'Grup Menü Yetkisi',
                'verbose_name_plural': 'Grup Menü Yetkileri',
                'unique_together': {('group', 'menu')},
            },
        ),
    ]
