# Generated by Django 6.0.3 on 2026-03-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_options_alter_bid_options_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_menu',
        ),
        migrations.DeleteModel(
            name='GroupMenuPermission',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
