# Generated by Django 6.0.3 on 2026-03-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_menu_parent_menu_delete_groupmenupermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/', verbose_name='İhale Görseli'),
        ),
    ]
