# Generated by Django 4.2.29 on 2026-04-04 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSpecificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='auction_specifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_files', to='auctions.auction')),
            ],
            options={
                'verbose_name': 'Şartname (PDF)',
                'verbose_name_plural': 'Şartname dosyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_gallery/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.auction')),
            ],
            options={
                'verbose_name': 'İhale görseli',
                'verbose_name_plural': 'İhale görselleri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
