# Generated by Django 4.2.29 on 2026-04-05 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0007_auctionwatchlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionWinNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_notifications', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_win_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kazanım bildirimi',
                'verbose_name_plural': 'Kazanım bildirimleri',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='auctionwinnotification',
            constraint=models.UniqueConstraint(fields=('user', 'auction'), name='unique_auction_win_notification_per_user_auction'),
        ),
    ]
