# Generated by Django 4.2.29 on 2026-04-06 21:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_win_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), help_text='KDV oranı (örn: 0.18 için %18)', max_digits=3),
        ),
    ]
